#name: Build android-app && add to GitHub artifacts
#
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#
#jobs:
#  build:
#    name: Build
#    runs-on: ubuntu-latest
#    defaults:
#     run:
#      working-directory: ./mobile
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Setup Node JS
#        uses: actions/setup-node@master
#
#      # - name: set up JDK 1.8
#      #   uses: actions/setup-java@v1
#      #   with:
#      #    java-version: 1.8
#
#      - name: Install dependencies
#        run: npm install --force
#
#      # - name: Build android
#      #   run: npm run cd android && ./gradlew assembleDebug
#
#      - name: Cache Gradle Wrapper
#        uses: actions/cache@v2
#        with:
#          path: ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
#
#      - name: Cache Gradle Dependencies
#        uses: actions/cache@v2
#        with:
#          path: ~/.gradle/caches
#          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-caches-
#
#      - name: Make Gradlew Executable
#        run: cd android && chmod +x ./gradlew
#
#      - name: Build Android App Bundle
#        run: |
#          cd android && ./gradlew bundleRelease --no-daemon
#
#      - name: Sign App Bundle
#        id: sign_app
#        uses: r0adkll/sign-android-release@v1
#        with:
#          releaseDirectory: android/app/build/outputs/bundle/release
#          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
#          alias: ${{ secrets.ANDROID_SIGNING_ALIAS }}
#          keyStorePassword: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
#          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
#
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: Benefit
#          path: ${{steps.sign_app.outputs.signedReleaseFile}}

name: Build android-app && add to GitHub artifacts
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobile
    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: |
          npm install --force

  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobile
    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: |
          npm install --force

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android Debug
        run: |
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
          cd android && ./gradlew assembleDebug

      - name: upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: Benefit.apk
          path: ./android/app/build/outputs/apk/debug/app-debug.apk

      - name: Send telegram message on new app build
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            Application: ${{ steps.upload-artifact.outputs.name }}
