name: Continuous Integration

on:
  pull_request:
    branches: ['**']

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install npm dependencies
        run: npm ci --force

      - name: Run linter
        run: echo 'Running linter...'

      - name: Run unit tests
        run: echo 'Running tests...'

      - name: Run TS Check
        run: yarn tsc
